
### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "32@gmail.com",
  "password": "123"
}

### Signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "32@gmail.com",
  "password": "123"
}


### Find user
GET http://localhost:3000/auth/3

### Find user
GET http://localhost:3000/auth?email=aaa@gmail.com

### Update user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "password": "aaa@gmail.com"
}

### Delete user
DELETE http://localhost:3000/auth/4