### 새로운 유저 생성
POST http://localhost:3000/users
Content-Type: application/json

{
  "nickname" : "고성인",
  "email" : "jjjk0605@naver.com",
  "password" : "password123"
}

### 모든 유저 조회
GET http://localhost:3000/users